Company.Test.PL/Controllers/DepartmentController.cs
using AutoMapper;
using Company.Test.BLL.Interfaces;
using Company.Test.BLL.Repositories;
using Company.Test.DAL.Models;
using Company.Test.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Company.Test.PL.Controllers
{
	[Authorize]
	public class DepartmentController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper _mapper;

        public DepartmentController( IUnitOfWork unitOfWork, IMapper mapper)
        {
            this.unitOfWork = unitOfWork;
            this._mapper = mapper;
        }


        //----------------------------------------------------Get All------------------------
        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var departments= await unitOfWork.departmentRepository.GetAllAsync();
            var result = _mapper.Map<IEnumerable<DepartmentVM>>(departments);
            return View(result);
        }

        //----------------------------------------------Details----------------------------------

        [HttpGet]
        public async Task<IActionResult> Details(int id,string ViewName = "Details") 
        {
            var department =await unitOfWork.departmentRepository.GetAsync(id);
            if (department is not null) 
            {
                var result=_mapper.Map<DepartmentVM>(department);
                return View(ViewName, result);
            }
            return NotFound();
        }



        //--------------------------------------------------Craete------------------------------------------------

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]    //تمنع اي ابلكيشن خارجي يكلم الابلكيشن ده زي Postman
        public async Task<IActionResult> Create(DepartmentVM departmentvm)
        {
            if (ModelState.IsValid)       //تعمل تاكيد علي الداتا الي رجعالي صح ولا لا
            {
                var result = _mapper.Map<Department>(departmentvm);
                var count=await unitOfWork.departmentRepository.AddAsync(result);    //لو الراجع صفر يبقي في ايرور ومتعملوش سيف لو واجد يبقي تمام

                if (count > 0) 
                {
                   return RedirectToAction("Index");
                }
                    return BadRequest();
            }
            return View(departmentvm);
        }


        //-------------------------------------------------------Edit-----------------------------------------------------


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            return await Details(id, "Edit");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]    //تمنع اي ابلكيشن خارجي يكلم الابلكيشن ده زي Postman
        public async Task<IActionResult> Edit([FromRoute]int? id ,DepartmentVM departmentvm)
        {
            if(id!= departmentvm.Id) return BadRequest();

            if (ModelState.IsValid)
            {
                var result = _mapper.Map<Department>(departmentvm);
                var count = await unitOfWork.departmentRepository.UpdateAsync(result); //لو الراجع صفر يبقي في ايرور ومتعملوش سيف لو واجد يبقي تمام

                if (count > 0)
                {
                    return RedirectToAction("Index");
                }
                return BadRequest();
            }
            return View(departmentvm);
        }



        //-------------------------------------------------------------Delete-----------------------------------------


        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            return await Details(id, "Delete");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]    //تمنع اي ابلكيشن خارجي يكلم الابلكيشن ده زي Postman
        public async Task<IActionResult> Delete([FromRoute]int? id ,DepartmentVM departmentvm)
        {
            if (id != departmentvm.Id) return BadRequest();
            var result=_mapper.Map<Department>(departmentvm);
            var count =await unitOfWork.departmentRepository.DeleteAsync(result);

                if (count > 0)
                {
                    return RedirectToAction("Index");
                }
                return BadRequest();
         
        }


    }
}

Company.Test.PL/Controllers/EmployeeController.cs
using AutoMapper;
using Company.Test.BLL.Interfaces;
using Company.Test.DAL.Models;
using Company.Test.PL.Helpers;
using Company.Test.PL.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;

namespace Company.Test.PL.Controllers
{
    [Authorize]
    public class EmployeeController : Controller
    {
        private readonly IUnitOfWork unitOfWork;
        private readonly IMapper _mapper;

        public EmployeeController(IUnitOfWork unitOfWork, IMapper mapper)
        {
            this.unitOfWork = unitOfWork;
            _mapper = mapper;
        }


        //-----------------------------------------------------------GetAll-----------------------------------------

        public async Task<IActionResult> Index(string InputSearch)
        {
            var employees=Enumerable.Empty<Employee>();
            if (InputSearch.IsNullOrEmpty())
            {
                 employees = await unitOfWork.employeeRepository.GetAllAsync();
            }
            else 
            {
                 employees =await unitOfWork.employeeRepository.GetByNameAsync(InputSearch);
            }

            var reesult = _mapper.Map<IEnumerable<EmployeeVM>>(employees);

            return View(reesult);
        }


        //-----------------------------------------------------------Details-----------------------------------------


        [HttpGet]
        public async Task<IActionResult> Details(int id, string ViewName = "Details")
        {
            var employee = await unitOfWork.employeeRepository.GetAsync(id);

            if (employee is not null)
            {
                var employeevm = _mapper.Map<EmployeeVM>(employee);
                return View(ViewName, employeevm);
            }
            return NotFound();
        }



        //-----------------------------------------------------------Create-----------------------------------------

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var departments= await unitOfWork.departmentRepository.GetAllAsync();
           var result= _mapper.Map<IEnumerable<DepartmentVM>>(departments);

            ViewData["Departments"] = result;
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]    //تمنع اي ابلكيشن خارجي يكلم الابلكيشن ده زي Postman
        public async Task<IActionResult> Create(EmployeeVM employeevm)
        {
            if (ModelState.IsValid)       //تعمل تاكيد علي الداتا الي رجعالي صح ولا لا
            {
                if (employeevm.Image is not null) 
                {
                    employeevm.ImageName = DocumentSettings.Upload(employeevm.Image, "Images");   // خزن الصوره وهات اسمها
                }

                var employee =_mapper.Map<Employee>(employeevm);

                var count = await unitOfWork.employeeRepository.AddAsync(employee);    //لو الراجع صفر يبقي في ايرور ومتعملوش سيف لو واجد يبقي تمام

                if (count > 0)
                {
                    return RedirectToAction("Index");
                }
                return BadRequest();
            }
            return View(employeevm);
        }



       //--------------------------------------------------------Edit------------------------------------------------

        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            var departments =await unitOfWork.departmentRepository.GetAllAsync();
            var result = _mapper.Map<IEnumerable<DepartmentVM>>(departments);
            ViewData["Departments"] = result;
            return await Details(id, "Edit");
        }



        [HttpPost]   // Get data and save it in DB
        [ValidateAntiForgeryToken] //Refuse any out app to contact with this method 
        public async Task<IActionResult> Edit([FromRoute] int? id, EmployeeVM employeevm)
        {
            if (id != employeevm.Id) return BadRequest();   //Check if any one send wrong data

            if (ModelState.IsValid)
            {
                if (employeevm.ImageName is not null) 
                    DocumentSettings.Delete(employeevm.ImageName, "Images");  //Upload Image to wwwroot


                if(employeevm.Image is not null)
                    employeevm.ImageName = DocumentSettings.Upload(employeevm.Image, "Images");   //Save image && return name


                var employee=_mapper.Map<Employee>(employeevm); //map to employee
                var count =await unitOfWork.employeeRepository.UpdateAsync(employee);

                if (count > 0) //Done
                {
                    return RedirectToAction("Index");
                }
                return BadRequest();
            }
            return View(employeevm);
        }






        //---------------------------------------------------Delete------------------------------------------------

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            return await Details(id, "Delete");
        }




        [HttpPost]
        [ValidateAntiForgeryToken]    //تمنع اي ابلكيشن خارجي يكلم الابلكيشن ده زي Postman
        public async Task<IActionResult> Delete([FromRoute] int? id, EmployeeVM employeevm)
        {
            if (id != employeevm.Id) return BadRequest();


            var employee= _mapper.Map<Employee>(employeevm);
            var count =await unitOfWork.employeeRepository.DeleteAsync(employee);

            if (count > 0)
            {
                if (employeevm.ImageName is not null)
                {
                    DocumentSettings.Delete(employeevm.ImageName, "Images");  //اتاكد الاول انه اتمسح وبعدين امسح الصوره
                }
                return RedirectToAction("Index");
            }
            return BadRequest();

        }
    }
}

Company.Test.PL/Controllers/userController.cs
using Company.Test.BLL;
using Company.Test.BLL.Interfaces;
using Company.Test.DAL.Models;
using Company.Test.PL.Helpers;
using Company.Test.PL.ViewModels;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.IdentityModel.Tokens;

namespace Company.Test.PL.Controllers
{
	public class userController : Controller
	{
		//Get , GetAll , Update  ,Delete
		private readonly UserManager<ApplicationUser> userManager;


		public userController(UserManager<ApplicationUser> userManager)
        {
			this.userManager = userManager;
		}

		public async Task<IActionResult> Index(string InputSearch)
		{
			var users = Enumerable.Empty<UserVM>();
			if (InputSearch.IsNullOrEmpty())
			{
				users = await userManager.Users.Select(u=> new UserVM() {   //Mapping from user to uservm

					Id = u.Id,
					FirstName = u.FirstName,
					LastName = u.LastName,
					Email=u.Email,
					Roles=userManager.GetRolesAsync(u).Result

				}).ToListAsync();
			}
			else
			{
				users = await userManager.Users.Where(u => u.Email.
				                                ToLower().
				                                Contains(InputSearch.ToLower()))
					                            .Select(u => new UserVM()
								                {   //Mapping from user to uservm
								              
								              	  Id = u.Id,
								              	  FirstName = u.FirstName,
								              	  LastName = u.LastName,
								              	  Email = u.Email,
								              	  Roles = userManager.GetRolesAsync(u).Result
								              
								                }).ToListAsync();

			}

			return View(users);
		}

		 

        //-----------------------------------------------------------Details-----------------------------------------


        [HttpGet]
        public async Task<IActionResult> Details(string? id, string ViewName = "Details")
        {

			if (id is null)
				return BadRequest();

			var userFromDb = await userManager.FindByIdAsync(id);

            if (userFromDb is not null)
            {

				var user = new UserVM()
				{
					Id = userFromDb.Id,
					FirstName = userFromDb.FirstName,
					LastName = userFromDb.LastName,
					Email=userFromDb.Email,
					Roles = userManager.GetRolesAsync(userFromDb).Result
                };

                return View(ViewName, user);
            }
            return NotFound();
        }






        //--------------------------------------------------------Edit------------------------------------------------

        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            return await Details(id, "Edit");
        }



        [HttpPost]
        [ValidateAntiForgeryToken]    //تمنع اي ابلكيشن خارجي يكلم الابلكيشن ده زي Postman
        public async Task<IActionResult> Edit([FromRoute] string? id, UserVM userVM)
        {
            if (id != userVM.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {

                var userFromDb = await userManager.FindByIdAsync(id);

                if (userFromDb is not null)
                {
                    userFromDb.FirstName = userVM.FirstName;
                    userFromDb.LastName = userVM.LastName;
                    userFromDb.Email = userVM.Email;

                    await userManager.UpdateAsync(userFromDb);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(userVM);
        }






        //---------------------------------------------------Delete------------------------------------------------

        [HttpGet]
        public async Task<IActionResult> Delete(string id)
        {
            return await Details(id, "Delete");
        }




        [HttpPost]
        [ValidateAntiForgeryToken]    //تمنع اي ابلكيشن خارجي يكلم الابلكيشن ده زي Postman
        public async Task<IActionResult> Delete([FromRoute] string? id, UserVM userVM)
        {

            if (id != userVM.Id)
                return BadRequest();

            if (ModelState.IsValid)
            {

                var userFromDb = await userManager.FindByIdAsync(id);

                if (userFromDb is not null)
                {
                    userManager.DeleteAsync(userFromDb);
                    return RedirectToAction(nameof(Index));
                }
                return NotFound();
            }
            return View(userVM);

        }



    }
}

Company.Test.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	<link href="css/style.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<link href="~/css/SignUp.css" rel="stylesheet">
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		<h1>Creative SignUp Form</h1>
		@RenderBody();
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
</html>

Company.Test.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Company.Test.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Company.Test.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company.Test.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Department" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                      
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="user" asp-action="Index">Users</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link btn btn-danger" asp-area="" asp-controller="Account" asp-action="SignOut">LogOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Company.Test.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ClientSideValidation", required: false)

</body>
</html>